[programs.localnet]
coherence_beamsplitter = "Cm921Cpvi9CbeWyrjTUFccdaHTZwcQjJmEuGhNTo2NTh"

[programs.devnet]
coherence_beamsplitter = "Cm921Cpvi9CbeWyrjTUFccdaHTZwcQjJmEuGhNTo2NTh"

[programs.mainnet]
coherence_beamsplitter = "Cm921Cpvi9CbeWyrjTUFccdaHTZwcQjJmEuGhNTo2NTh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*"

[test]
startup_wait = 30000
