[programs.localnet]
coherence_beamsplitter = "A29uL2xu7njxWSYSpsgYyWivAJ5DmmVC48hH6dnbJBq9"

[programs.devnet]
coherence_beamsplitter = "A29uL2xu7njxWSYSpsgYyWivAJ5DmmVC48hH6dnbJBq9"

[programs.mainnet]
coherence_beamsplitter = "A29uL2xu7njxWSYSpsgYyWivAJ5DmmVC48hH6dnbJBq9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*"

[test]
startup_wait = 30000
clone = [
  { address = "A8YFbxQYFVqKZaoYJLLUVcQiWP7G2MeEgW5wsAQgMvFw" }, 
  { address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin" }, 
  { address = "9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT" }, 
  { address = "14ivtgssEBoBjuZJtSAPKYgpUK7DmnSwuPMqJoVTSgKJ" },
  { address = "6wLt7CX1zZdFpa6uGJJpZfzWvG6W9rxXjquJDYiFwf9K" }
]
validator = {url = "m"}
