name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Yarn dependencies
      run: yarn --verbose
    - name: Install Solana
      run: 'sh -c "$(curl -sSfL https://release.solana.com/v1.9.3/install)"'
    - name: Install Anchor
      run: npm i -g @project-serum/anchor-cli
    - run: cargo build-bpf --version
    - run: rustup --version
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: yarn test
